version: '3.8'
services:
  app:
    container_name: logistica-app
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/logistica
      - JWT_SECRET=supersecreto123
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: logistica-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistica
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
