-- AlterTable
ALTER TABLE `Camion` ALTER COLUMN `tipo` DROP DEFAULT;

-- AlterTable
ALTER TABLE `Usuario` ADD COLUMN `dni` VARCHAR(191) NULL,
    ADD COLUMN `estado` VARCHAR(191) NOT NULL DEFAULT 'VERIFICANDOSE',
    ADD COLUMN `vat` VARCHAR(191) NULL;
